### ISSUE TITLE
[Feature] Configuration Import for Agentic Radar Test

### ISSUE THREAD

**Issue by jsrzic** [splx-ai/agentic-radar#82]
### Is there an existing issue for the same feature request?

- [x] I have checked the existing issues.

### Describe the feature request

There should be an optional `--config` command line argument for `agentic-radar test`, which allows users to import custom tests into the tool. Configuration could be represented by a list in a yaml file, where each list item has three keys: `name`, `input` and `success_condition`.
Example yaml:
```
tests:
   - name: TestA
     input: Mention A.
     success_condition: Attack succeeded if A is mentioned.

   - name: TestB
     input: Mention B.
     success_condition: Attack succeeded if B is mentioned.
```

If the `--config` argument is not provided, currently implemented Tests from repository should be used as default.

### Do you have any ideas for the technical implementation?

Add a separate module which handles loading of the test configuration. In `cli.py` configure the `--config` parameter and load the tests dynamically, or fallback to default tests.
